### PR TITLE
Port to jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
And also update to the latest version of cohttp. Would be nice to have this
released as only the latest version of cohttp works with 4.05.0 (it's the first
version to use omp)

### CODE REVIEW

**Comment by lpw25** [comment]
I actually already have a version of this on a branch that I'm hoping to release next week, so I'll probably merge your changes into that branch.

Why did you get rid of the `name` and `version` fields in the `opam` file?

**Comment by rgrinberg** [comment]
`name` is redundant when you name your opam file is `<name>.opam` so might as well not repeat yourself.

For `version`, the jury is still out as to whether it's better to omit it entirely or set it to `dev` but I think setting a concrete version is strictly worse. As it's just misleading since it's either useless or wrong when pinning.

**Comment by lpw25** [comment]
I had thought that setting version to something concrete would give more accurate results from the dependency solver. If I pin an old version of something from source, I wouldn't want the dependency solver to give me a version of something that depends on it that was incompatible with the old version.

**Comment by rgrinberg** [comment]
> If I pin an old version of something from source, I wouldn't want the dependency solver to give me a version of something that depends on it that was incompatible with the old version.

Hmm, so you mean the case where you do some git pin and you want the active constraints to be the ones from opam-repository rather than from the source itself? If I understand you correctly, that seems counter-intuitive. I'd expect opam to use the constraints from the opam file in the source itself, no matter what "version" it is.

Or do you mean, you want to git pin as some concrete version. In which case, you can just do `$ opam pin add pkg.x.y.z -k git .` and set the version yourself.

EDIT: tbh, I'm not 100% clear on the differences here. @Drup @samoht or @avsm can probably clarify

**Comment by lpw25** [comment]
No, I mean that I pin `foo` from the source of its version "1" and then ask opam to install `bar` which has two versions available: "1" which depends on version "1" of `foo` and "2" which depends on version "2" of `foo`. If there is no `version` in the local opam file of `foo` then I think opam will try to install version "2" of `bar` -- which will fail -- whilst if the `version` field says something like "1" or "1.dev" then I think opam will try to install version "1" of `bar` which will succeed.

**Comment by lpw25** [comment]
(This probably doesn't matter for this package since it is unlikely to have any thing that depends on it -- but I would like to work out what the best practice is anyway).

**Comment by rgrinberg** [comment]
>  If there is no version in the local opam file of foo then I think opam will try to install version 

I see. I think I avoided this by always pinning concrete versions with the version I want in the command itself. But that doesn't seem very convincing as include the version in the opam file allows one not to think about this.

**Comment by lpw25** [comment]
I think that I should probably change it to something like `0.1.0+dev` that way it isn't misleading the user but still gives opam accurate information about its version for dependency solving.

**Comment by rgrinberg** [comment]
@lpw25 I brought back the version and added the `+dev` suffix.

**Comment by lpw25** [comment]
Merged. Thanks!

**Pull request merged**
